trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Iniciando pipeline...
  displayName: 'Inicio del pipeline'

- task: SonarQubePrepare@5
  displayName: 'Conexi칩n con SonarQube'
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'VS_Entregable_4.1_VS_Entregable_4.1_AYyYM5QkNlNANsh9XTim'
    cliProjectName: 'VS Entregable 4.1'
    cliProjectVersion: 1.0
    cliSources: .

- script: |
    docker-compose up -d
  displayName: 'Docker Compose Up'

- task: SonarQubeAnalyze@5
  displayName: 'An치lisis de c칩digo'
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'

- task: SonarQubePublish@5
  displayName: 'Publicaci칩n de los resultados'
  inputs:
    pollingTimeoutSec: '300'
