apiVersion: v1 # Versión de la API de Kubernetes a utilizar
kind: Service # Tipo de archivo de configuración (Service)
metadata: # Metadatos del recurso
  name: service-drupal # Nombre del servicio
spec: 
  selector: # El Servicio (Service) selecciona los Pods que se expondrán en función de sus etiquetas.
    app: drupal # Deben coincidir con las especificadas para los Pods en el recurso de Despliegue (en nuestro caso drupal).
  type: NodePort # Puerto del Nodo
  ports:
    - name: http # Método de solicitud
      port: 80 # Escucha solicitudes en el puerto 80
      nodePort: 30080 # Las reenvía al puerto 30080 del Pod de destino