apiVersion: apps/v1 # Versión de este tipo de recurso (apps/v1)
kind: Deployment # Tipo de recurso (Deployment)
metadata:
 name: drupal # Nombre de este recurso específico
spec:
  replicas: 1
  selector:
    matchLabels: # selecciona aquellos Pods con una etiqueta (app:drupal) para que pertenezcan a este Deployment
      app: drupal
  template:
    metadata:
      labels: # Define una etiqueta (drupal) para los Pods que envuelven tu contenedor
        app: drupal
    spec:
      containers:
      - name: drupal # Nombre para el contenedor (drupal)
        image: drupal:latest # Nombre de la imagen Docker a usar (drupal:latest)
        ports:
          - containerPort: 80 # Puerto en el que exponemos el contenedor
        volumeMounts:
          - name: drupal-persistent-storage # Define el nombre del volumen
            mountPath: /drupal # Especifica directorio de montaje
      volumes: 
        - name: drupal-persistent-storage # Define el nombre del volumen
          persistentVolumeClaim:
            claimName: drupal-pvc-claim # Define el nombre que se utilizará para solicitar un volumen persistente del cluster de Kubernetes