apiVersion: v1 # Versión de la API de Kubernetes a utilizar
kind: Service # Tipo de archivo de configuración (Service)
metadata: # Metadatos del recurso
  name: service-mysql # Nombre del servicio
spec: 
  selector: # El Servicio (Service) selecciona los Pods que se expondrán en función de sus etiquetas.
    app: mysql # Deben coincidir con las especificadas para los Pods en el recurso de Despliegue (en nuestro caso drupal).
  type: ClusterIP # Puerto del Nodo
  ports:
    - name: http # Método de solicitud
      port: 3306
      targetPort: 3306