apiVersion: apps/v1 # Versión de este tipo de recurso (apps/v1)
kind: Deployment # Tipo de recurso (Deployment)
metadata:
 name: mysql # Nombre de este recurso específico
spec:
 selector:
    matchLabels: # selecciona aquellos Pods con una etiqueta (app:mysql) para que pertenezcan a este Deployment
      app: mysql
 template:
    metadata:
      labels: # Define una etiqueta (app:mysql) para los Pods que envuelven tu contenedor
        app: mysql
    spec:
      containers:
      - name: mysql # Nombre para el contenedor (mysql)
        image: mysql:latest # Nombre de la imagen Docker a usar (mysql:latest)
        ports:
        - containerPort: 3306 # Puerto en el que exponemos el contenedor
        env: # Variables de entorno
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: drupal
        - name: MYSQL_USER
          value: drupal
        - name: MYSQL_PASSWORD
          value: drupal
        volumeMounts:
          - name: mysql-persistent-storage # Define el nombre del volumen
            mountPath: /mysql # Especifica directorio de montaje
      volumes: 
      - name: mysql-persistent-storage # Define el nombre del volumen
        persistentVolumeClaim:
          claimName: mysql-pvc-claim # Define el nombre que se utilizará 
          # para solicitar un volumen persistente del cluster de Kubernetes