import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script

object Project : PipelineProject({
    buildType {
        id("Build")
        steps {
            script {
                scriptContent = "npm install" // Instalar dependencias
            }
        }
    }

    buildType {
        id("Test")
        dependencies {
            snapshot("Build") {}
        }
        steps {
            script {
                scriptContent = "./teamcity/scripts/test.sh"
            }
        }
    }

    buildType {
        id("Deliver")
        dependencies {
            snapshot("Test") {}
        }
        steps {
            script {
                scriptContent = "./teamcity/scripts/deliver.sh"
            }
            script {
                scriptContent = "./teamcity/scripts/kill.sh"
            }
        }
    }
})
